### ISSUE TITLE
FPVS preferences do not appear in Tools -> Add-on Options menu

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/folder-pane-view-switcher#1]
There should be a menu command underneath Tools -> Add-on Options to open the Folder Pane View Switcher preferences.

**Comment by jikamens** [comment]
Workaround: Open the add-ons page, click the three little dots to the right of the add-on name, and select "Preferences".

**Comment by jikamens** [comment]
Apparently this is going away on purpose, so never mind.

**Comment by fgn-git-hub** [comment]
Exactly, even i checked with the tb add-on team said the same. currently this is the only option available for the options page .
