### ISSUE TITLE
FPSV not working properly

### ISSUE THREAD

**Issue by PyBonnetainNesterenko** [Extended-Thunder/folder-pane-view-switcher#10]
(sorry for the title not being really meaningful).

Installed FPSV 4.0.1 on Tb 78.4.0, Linux host. Installation went ok, and FPSV works great. Closed Tb, reopened, nothing works anymore.

The error console gives :
- on Tb startup, « TypeError: main_window is null » (backgrnd-Implementation.js:298:30)
- when pressing an arrow to change views : « TypeError: FolderPaneSwitcher.views is null » (backgrnd-Implementation.js:224:15)
- when opening the FPSV preference window : « [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///XXX/.thunderbird/ProfileDir/extensions/FolderPaneSwitcher@kamens.us.xpi!/chrome/content/options-Implementation.js :: getBoolPref :: line 55"  data: no] » (options-Implementation.js:55:35)
- when playing with the preferences : « Uncaught (in promise) Error: An unexpected error occurred » (undefined)
and main_window is null 7 backgrnd-Implementation.js:105

Tb has no access to the outside (filewall and proxy blocked), if this may be useful.

**Comment by r-a-y** [comment]
I'm experiencing the same problems. FPSV 4.0.1, TB 78.4.0 on Windows 10 over here.

**Comment by PyBonnetainNesterenko** [comment]
Dunno if it was patch d65f376 or some other later, but release 4.0.2 from today seems free of this bug. Thanks !
