### ISSUE TITLE
Arrow head rotation does nothing

### ISSUE THREAD

**Issue by snowbound** [Extended-Thunder/folder-pane-view-switcher#12]
Just upgraded from TB 68 to TB 78.4.3 x64 on Windows 10 2004  and notice that the arrow heads do nothing. Clicking on the left or right ones does not rotate through the folders. Going into options for the extension and turning off the option for "Show Folder Pane Arrorws" does nothing either the arrows still show up in TB. Is this a known issue?

**Comment by jikamens** [comment]
Same as #10, I think.
