### ISSUE TITLE
Switcher arrow buttons do not work at all

### ISSUE THREAD

**Issue by lsteeger** [Extended-Thunder/folder-pane-view-switcher#14]
TB 78.5.0 and FPVS 4.0 

FPVS 4.0 installed from [github](https://github.com/Extended-Thunder/folder-pane-view-switcher/releases/download/v4.0/FolderPaneSwitcher.xpi) xpi file.

Console messages:

console.log: WebExtensions: 78.5.0
console.log: WebExtensions: extensions.FolderPaneSwitcher TRACE WindowObserver.observe
console.log: WebExtensions: called from the observer
JavaScript error: jar:file:///home/user/.thunderbird/profiledir.default/extensions/FolderPaneSwitcher@kamens.us.xpi!/backgrnd-Implementation.js, line 298: TypeError: main_window is null
JavaScript error: undefined, line 0: Error: An unexpected error occurred
JavaScript error: jar:file:///home/user/.thunderbird/profiledir.default/extensions/FolderPaneSwitcher@kamens.us.xpi!/backgrnd-Implementation.js, line 224: TypeError: FolderPaneSwitcher.views is null
JavaScript error: jar:file:///home/user/.thunderbird/profiledir.default/extensions/FolderPaneSwitcher@kamens.us.xpi!/backgrnd-Implementation.js, line 224: TypeError: FolderPaneSwitcher.views is null
JavaScript error: jar:file:///home/user/.thunderbird/profiledir.default/extensions/FolderPaneSwitcher@kamens.us.xpi!/backgrnd-Implementation.js, line 224: TypeError: FolderPaneSwitcher.views is null
JavaScript error: jar:file:///home/user/.thunderbird/profiledir.default/extensions/FolderPaneSwitcher@kamens.us.xpi!/backgrnd-Implementation.js, line 200: TypeError: FolderPaneSwitcher.views is null

As an additional note, the arrow buttons work immediately after installing the addon and selecting the configuraton option to show the arrow buttons, but are not functional ever again once TB is stopped and started.

**Comment by snowbound** [comment]
Seems to be the same thing I report and was told the same as #10

**Comment by swerthei** [comment]
Same issue. Great extension. I just upgraded TB to 78.6.1 and now this extension works after installing but not after restarting TB.

**Comment by MacGyver00** [comment]
Similar here.  
TB 78.6.1 portable:  after installation of the add-on, buttons are here but inactive
In previous (portable) TB versions: after fresh add-on installation, buttons were working until TB restart.

**Comment by netjeff** [comment]
I've had the same symptoms since release. Using the drop-down works, but the buttons do not.

**Comment by netjeff** [comment]
Good news (for me at least):  Just updated TB to 78.11.0 and the buttons now work.  This is with FPV 4.0.1.

**Comment by darose** [comment]
That's only temporary.  The first time after a TB upgrade, the arrows return.  Next time you start it up they will not appear again.

I'm not holding my breath that this bug is going to be fixed any time soon ... :-(

**Comment by netjeff** [comment]
I've restarted TB a few times, and I'm happy to say the buttons still working for me.

**Comment by MacGyver00** [comment]
I confirm: In my win 10 laptop, with TB 78.11.0 portable, buttons are fully functional!  
In previous versions since 78.6.1 (see my comment above) buttons were functional until TB restart.

**Comment by darose** [comment]
I'm using TB 78.11.0 on Linux and the buttons only appear after each version upgrade.  The next time I restart they're gone.

**Comment by netjeff** [comment]
More details:  Win10 laptop, with TB 78,11.0 regular install (not portable), with FPV 4.0.1.  Buttons working fine across restarts since updating to TB 78.11.0

**Comment by rmeden** [comment]
Win10 ,  TB 78,11.0   I also think the buttons stayed after a restart after 78.11.0.... Until they don't.  It stopped after the OS reboot (windows patches).

**Comment by netjeff** [comment]
More data points:  Applied latest Win10 updates, rebooted, buttons still working.

**Comment by lsteeger** [comment]
I removed Folder Pane View Switcher installed via xpi.
Stopped/started TB.
Installed from addons.thunderbird.net.
Arrows worked.
Stopped/started TB.
Arrows worked.

Now at:
TB 78.11.0 (64bit)
FPVS 4.0.1

The fix does indeed seem to be in TB 78.11.0

**Comment by rmeden** [comment]
I removed the plugin.
Restarted T-Bird (78.11.0)
Installed the plugin (got arrows)
Restarted T-Bird
No arrows. :(

Not fixed for me.

**Comment by rmeden** [comment]
I found an exentions debug pane I've never noticed before.. here are the errors there.  I don't think I ever used a twitter extension and can't find a Extension.jsm file in %appdata% or Program Files (x86)

<pre>
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
TypeError: singletons is null
3 ActorManagerChild.jsm:297:32
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] L10nRegistry.jsm:658:19
Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND) Extension.jsm:570
1624544722080	addons.xpi	WARN	Exception running bootstrap method startup on twitter@search.mozilla.org: Error: Error while loading 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/omni.ja!/chrome/messenger/search-extensions/twitter/manifest.json' (NS_ERROR_FILE_NOT_FOUND)(resource://gre/modules/Extension.jsm:570:20) JS Stack trace: readJSON/</<@Extension.jsm:570:20
onStopRequest@NetUtil.jsm:128:18
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). panel.js:78:24
Webconsole context has changed
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). panel.js:78:24
</pre>

**Comment by darose** [comment]
> I removed the plugin.
> Restarted T-Bird (78.11.0)
> Installed the plugin (got arrows)
> Restarted T-Bird
> No arrows. :(
> 
> Not fixed for me.

Not fixed for me either.

**Comment by snowbound** [comment]
Has been working fine for me on TB 78.11.0 (64-bit) on Windows10 20H1. Try disabling any other extensions you have enabled.

**Comment by lsteeger** [comment]
This issue has returned after 2 weeks.

Now the arrows do not even appear! 

Prior to TB 78.11.0 the arrows appeared but did not function when clicked.

**Comment by PyBonnetainNesterenko** [comment]
Have you tried with latest FPV 4.0.2 (released Sep 2) ? This bug looks awfully like https://github.com/Extended-Thunder/folder-pane-view-switcher/issues/10, which is solved in the 4.0.2 release.

**Comment by lsteeger** [comment]
[Folder Pane View Switcher 4.0.2](https://addons.thunderbird.net/en-US/thunderbird/addon/folder-pane-view-switcher/?src=search) with [Thunderbird 78.14.0](https://www.thunderbird.net/en-US/thunderbird/78.14.0/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=78.14.0&channel=release&os=Linux&buildid=20210901192859) now working!

The TAG for the code is at [**v4.0.2**](https://github.com/Extended-Thunder/folder-pane-view-switcher/releases/tag/v4.0.2) although the _Latest Release_ here is still showing [**v4.0**.](https://github.com/Extended-Thunder/folder-pane-view-switcher/releases/tag/v4.0).

Luckily the Thunderbird Add-ons Repository has the fixed version.

Thank you.

**Comment by darose** [comment]
Please do not close this bug.  It is *not* fixed.  (Even with v4.0.2)  See attached.
![Screenshot_2021-09-08_13-47-59](https://user-images.githubusercontent.com/507237/132559266-0568f1cd-0e7a-4dac-a4bc-487b30c8657f.png)

**Comment by snowbound** [comment]
I have no problem on TB 78.14.0 and  4.0.2

**Comment by darose** [comment]
I'm not saying that you have no problem; I'm just saying that I do.  (Screenshot above doesn't lie!)  :-)  I'm using TB 78.14.0 on Arch Linux with FPVS v4.0.2

**Comment by darose** [comment]
And now, after an upgrade to TB 91.1.0, the plugin is disabled altogether.
