### ISSUE TITLE
arrows disappeared again today after auto update

### ISSUE THREAD

**Issue by dmcdivitt** [Extended-Thunder/folder-pane-view-switcher#15]
Last week it worked perfect. I was so happy! I closed Thunderbird, opened, closed, opened, and the arrows remained since last week. Today they disappeared again. If I install they appear until I close, but upon reopening they do not appear. This is the same exact problem the add-on has had a long time. I don't understand why it can't be fixed. It was working, but today's update spoiled it again. Can you just undo whatever you just did and queue for update again?

**Comment by jikamens** [comment]
Nothing has changed in the add-on. The problem is intermittent, so filing new issues about it will not help.
