### ISSUE TITLE
In TBird 91.6.2 FPVS Still Not Available

### ISSUE THREAD

**Issue by crablouis** [Extended-Thunder/folder-pane-view-switcher#20]
Still seeing: 

_"Manage Your Extensions | Folder Pne View Switcher (disabled"
"Folder Pan View Switcher is incompatible with Thunderbird 91.6.1."_

I've been seeing activity here, closures etc. Is FPVS now available? 
Should we be removing and reinstalling or something?

**Comment by opto** [comment]
here is a test version: https://github.com/opto/folder-pane-view-switcher/releases/tag/v5.1.2beta01

you are welcome to test, it is working on my win 11 and Ubntu 20 LTS.

Install by extra-> addons, cog symbol, install from file. I tested to install it over an old version which came over from TB 78 and that worked on win 11.

Please report any issues here, many thanks.

Klaus

**Comment by goozak** [comment]
Arrows are back! (Windows 10 Pro and TB 91.7.0)

**Comment by crablouis** [comment]
- Really happy to see this. **Thanks** so much for all the work. 
- Unfortunately, I'm in the middle of tax prep hell and cannot (ok, afraid to) test betas right now. 
- I look forward to seeing the fix come through the normal update mechanism.

**Comment by rmeden** [comment]
seems to work, but arrows don't show after restarting T-Bird.  They come back by disabling/re-enabling the add-on though.

**Comment by opto** [comment]
@rmeden : many thanks for the info. from which TB version and OS did you upgrade from? Or js it a clean install with no previous deactivated addon?

**Comment by bacchio66** [comment]
@rmeden : identical behaviour on my TB 91.7.0 64bit on Win 8.1. I had a previous deactivated addon. Thanks for your work

**Comment by rmeden** [comment]
@opto:  TB 91.7.0 32bit on Win 10.  Just like @bacchio66, was deactivate when I upgraded via file.   I didn't reinstall TB.

**Comment by hhaeb** [comment]
Thanks for the continuation of your  work! Here with TB91.7 and Win10  21H1 the arrows are visible after Installation of the addon and disappeared after restart of TB. After deactivating and reactivating the arrawos are visible again.

**Comment by opto** [comment]
thanks for the info. We are working on this, specifically on race conditions like adding the arrows to TB which then are later removed on the TB start.

**Comment by crablouis** [comment]
- It's great to see the activity on this. 
- Any forecast on an ETA for the distributed fix?
- Will final fix require re-installation of the extension, or will it come through the normal update mechanism?

**Comment by opto** [comment]
I think it will come soon, as standard update from ATN.

**Comment by crablouis** [comment]
Sounds like this is ready for distribution. 
It's not available yet through the Add-ons Manager UI. 
When will it be distributed?

**Comment by arndissler** [comment]
Closing the issue as Folder Pane View Switcher was already updated and released for Thunderbird v115.
