### ISSUE TITLE
Missing "Unread Compact" as an option

### ISSUE THREAD

**Issue by Taki-B** [Extended-Thunder/folder-pane-view-switcher#21]
I'm pretty sure that I could select a compact unread view in the past. Selecting Thunderbird's "Compact View" doesn't help because after once "All Folders" was selected, the "Compact View" gets resetted. I'm using a lot of e-mail accounts and getting rid of the account name lines would help.

**Comment by PyBonnetainNesterenko** [comment]
Same problem here as OP. The compact view is lost as soon as we switch views.
TB 91.10.0 on Linux Gentoo, version 5.2 of the plugin.

**Comment by arndissler** [comment]
I'm closing this issue as with Folder Pane View Switcher 6.0 the compact view has support for the compact view option.
