### ISSUE TITLE
FPVS enable at thunderbird 91.X startup 

### ISSUE THREAD

**Issue by zefilipe** [Extended-Thunder/folder-pane-view-switcher#23]
Hi,

Im using Thunderbird 91.8.1 and long waited FPVS 5.1.2 !

When Thunderbird starts, FPVS does not shows arrows to swap view, and every time its starts i be disable and enable FPVS !

But if its a way to do this. without enable/disable FPVS every start, it will be better !
Regards

**Comment by jobisoft** [comment]
Can you check if this issue has been fixed for you in the latest release for TB91 and TB102?
https://github.com/Extended-Thunder/folder-pane-view-switcher/releases/tag/v5.2
