### ISSUE TITLE
Feedback on 5.2

### ISSUE THREAD

**Issue by rmeden** [Extended-Thunder/folder-pane-view-switcher#25]
5.2 is retaining the arrows after restarting Thunderbird.

5.2 *lost* the arrows when Thunderbird upgraded to 91.10.0.   Disabling/enabling the add-on brought them back, and they come back with a Thunderbird restart.

Getting closer! (and unfortunately, may be harder to troubleshoot, as you can't test until there's a tbird update!)

**Comment by zefilipe** [comment]
Hi,

Im using this addon version 5.2, and that works well at startup in Thunderbird 91.10.0 !
Now isnt needed disable/enable this all times to start !

Maybe you have an addon that maybe blocks this ... try disable somme addons to check if its works !
Regards

**Comment by DarthVukster** [comment]
Just installed 5.2 on 91.10.0 Windows 10.  Arrows show up, but do not function.  Trying to open the Options for this Add-On produces the error "TypeError: FPVSOptions.prefs.prefs is undefined".

**Comment by ginzlo** [comment]
Having same issue as previous commenters above using 91.10.0 (64-bit) on Win10 Pro.

1. No function
2. Opening settings: "TypeError: FPVSOptions.prefs.prefs[view] is undefined
3. No folder views selectable
4. Seems like settings doe not work at all
5. When toggling in the view, nothing happens (with the arrows)

**Comment by ginzlo** [comment]
update... finally got this to work. 

i un-stalled the add-on.  then downloaded the file directly from author website [ folder_pane_view_switcher-5.2-tb.xpi ].  did manual install.  restart thunderbird.  

all is good and working now.

**Comment by ThatGuyFromHighRolls** [comment]
I followed ginzlo's method and it is now working in Thunderbird v91.1.0 on Linux Mint v20.2.

**Comment by DarthVukster** [comment]
I also followed ginzlo's method and was successful installing folder_pane_view_switcher-5.2-tb.xpi on 91.10.0 Windows 10.
Life is good again!
Thanks!

**Comment by arndissler** [comment]
Closing the issue as Folder Pane View Switcher is now compatible with Thunderbird v115.
