### ISSUE TITLE
Not functional with TB 

### ISSUE THREAD

**Issue by PotatoCarl** [Extended-Thunder/folder-pane-view-switcher#26]
- No function
- Opening settings: "TypeError: FPVSOptions.prefs.prefs[view] is undefined
- No folder views selectable
- Seems like settings doe not work at all
- When toggling in the view, nothing happens (with the arrows)
TB 91.10.0, Linux 64bit, Suse Tumbleweed

**Comment by ginzlo** [comment]
Having exact same issues, 91.10.0 (64-bit) on Win10 Pro.

**Comment by ginzlo** [comment]
update... finally got this to work. 

i un-stalled the add-on.  then downloaded the file directly from author website [ folder_pane_view_switcher-5.2-tb.xpi ].  did manual install.  restart thunderbird.  

all is good and working now.

**Comment by toxi22** [comment]
I confirm. The plugin has been updated and is not working.
The error is the same:
TypeError: FPVSOptions.prefs.prefs[view] is undefined

- No folder views selectable
- Seems like settings doe not work at all

OS: Windows 7 SP1 x64
Thunderbird: 91.10.0 (64-bit)

**Comment by PotatoCarl** [comment]
As @ginzlo wrote: yes, it can work but:
1. You can download the correct version from the extension repository at Mozilla
2. Deinstallation and reinstallation from file will NOT work but lead to a flickering behaviour and removal of the extension on next start (after installation it does not work)
3. I could not test this but I believe *you have to remove it forst and restart thunderbird*
4. When you install the newested version from the repository you have to restart thunderbird, open extensions, bear with the strange flickering, reinstall the plugin, remove the plugin, restart thunderbird, install the plugin, restart thunderbird and NOW it works
I suppose there is still a bug or two, but at last it works again. missed it so much... Thanks.

**Comment by toxi22** [comment]
> update... finally got this to work.
> 
> first i uninstalled the add-on. then downloaded the file directly from author website [ folder_pane_view_switcher-5.2-tb.xpi ]. did manual install. restart thunderbird.
> 
> all is good and working now.

I confirm. After these steps, the plugin works. Excellent!

**Comment by crablouis** [comment]
**Same problem.** 
_So:_ 

1. Removed the add-on
2. Restarted TB
3. Searched for add-on through extensions page in app
4. Loaded add-on
5. Works!

**Comment by arndissler** [comment]
I'm closing the issue as Folder Pane View Switcher is now compatible with the lastest Thunderbird version (Thunderbird v115 as at the time of writing).
