### ISSUE TITLE
Please give the option to just leave it alone ...

### ISSUE THREAD

**Issue by arfa-daily** [Extended-Thunder/folder-pane-view-switcher#35]
How do I get my Thunderbird 'home' page back to looking how it did yesterday ? I don't want all the icons to have changed. I was perfectly happy with them as they were ...

**Comment by jikamens** [comment]
The updates to the Thunderbird user interface in the new version of Thunderbird have nothing to do with Folder Pane View Switcher. No idea why you filed this issue here.
