### ISSUE TITLE
Add hot-keys for switching the folder view back and forth

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/folder-pane-view-switcher#6]
There should be hot-keys for switching the folder view back and forth.

Migrated from https://github.com/jikamens/folder-pane-view-switcher/issues/1, which was submitted by @filotn.

**Comment by arndissler** [comment]
There are shortcuts now:
`Alt+Shift+8` (Windows), `Ctrl+Shift+8` (Linux) and `Command+Shift+8` (macOS) to switch for the previous view, `Alt+Shift+9` (Windows), `Ctrl+Shift+9` (Linux) and `Command+Shift+9` (macOS) to switch to the next view.
