### ISSUE TITLE
FPVS not activated on newly opened TB windows

### ISSUE THREAD

**Issue by jikamens** [Extended-Thunder/folder-pane-view-switcher#9]
If you open a folder in a new TB window, FPVS is not activated on the folder list in the new window. There's a new window listener missing or acting too early or something?

**Comment by jikamens** [comment]
Note that, as described in #11, another issue that for some people the arrows aren't even activating properly on the first TB window that opens. Basically, whatever the FPVS code is doing to activate itself isn't aequately robust or reliable to ensure that it activates on every TB window.

**Comment by darose** [comment]
Just wondering if there's been any progress on this issue.  It pretty much renders the plugin inoperative right now.

**Comment by darose** [comment]
FYI, seems like upgrading to FF 78.6.0 might have made this issue go away.

**Comment by lsteeger** [comment]
> FYI, seems like upgrading to FF 78.6.0 might have made this issue go away.

 @darose , I don't think upgrading **FF** will fix **TB**. Please see #14

**Comment by darose** [comment]
Sorry, my bad - I wrote FF, when I meant TB.  (Now corrected above.)  My distro updated to that newer version of TB a couple of days ago, and it seems like the arrows having been showing up since then.  Will give it a few more days to confirm.

**Comment by lsteeger** [comment]
> Sorry, my bad - I wrote FF, when I meant TB. (Now corrected above.) My distro updated to that newer version of TB a couple of days ago, and it seems like the arrows having been showing up since then. Will give it a few more days to confirm.

No problem. Unfortunately, TB 78.6.0 did not solve the problem here. @lsteeger

**Comment by darose** [comment]
If it helps at all, these are the settings I have set up for the plugin.  Maybe check if yours are set similarly.

![Screenshot_2020-12-16_15-47-59](https://user-images.githubusercontent.com/507237/102404815-33c3cd80-3fb6-11eb-8561-aa2165c8dea3.png)

**Comment by darose** [comment]
Yeah, looks like I spoke too soon.  No folder pane arrows this morning.  :-(

Frustrating that it's taking so long for a fix ...

**Comment by darose** [comment]
I've noticed a pattern here:  seems like any time the TB package gets upgraded, the arrow keys will suddenly start working again that day.  (I noticed because my distro had a package upgrade today.)  Not sure what the trigger is there, but it does seem deterministic.

**Comment by darose** [comment]
Looks like these issues aren't getting fixed any time soon.  :-(  That's a little disappointing, as I participated in last year's Kickstarter campaign hoping for this plugin to get some love.

**Comment by jikamens** [comment]
Not ignoring it, just don't have anything new to add. :-( I'm sorry about the delays. The pandemic and other circumstances in my life have made it more challenging than I had hoped to get this stuff done. It _will_ be fixed. I just don't quite know when yet. Sorry again.

**Comment by lsteeger** [comment]
FPVS v5.2 works fine on TB 102.2.
No problems during restarts, etc.

**Comment by arndissler** [comment]
The issue seems to be fixed, so I'm closing the issue.
